[package]
name = "ttyloop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aglet = "0.5.1"
cursive = "0.20.0"
fastrand = "2.0.1"
getset = "0.1.2"
itertools = "0.12.0"
